# Generated by Django 5.1.7 on 2025-07-27 00:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "codigo",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                ("preco_custo", models.DecimalField(decimal_places=2, max_digits=10)),
                ("preco_venda", models.DecimalField(decimal_places=2, max_digits=10)),
                ("estoque_minimo", models.PositiveIntegerField(default=0)),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="loja.categoria"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Variacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tamanho", models.CharField(blank=True, max_length=10)),
                ("cor", models.CharField(blank=True, max_length=50)),
                ("quantidade", models.PositiveIntegerField(default=0)),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="loja.produto"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MovimentacaoEstoque",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade", models.PositiveIntegerField()),
                (
                    "tipo",
                    models.CharField(
                        choices=[("E", "Entrada"), ("S", "Saída")], max_length=1
                    ),
                ),
                ("data", models.DateTimeField(auto_now_add=True)),
                ("motivo", models.CharField(blank=True, max_length=100)),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="loja.produto"
                    ),
                ),
                (
                    "variacao",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="loja.variacao",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Venda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome_cliente",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "telefone_cliente",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("data", models.DateTimeField(auto_now_add=True)),
                ("valor_total", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "forma_pagamento",
                    models.CharField(
                        choices=[
                            ("DIN", "Dinheiro"),
                            ("PIX", "PIX"),
                            ("CART", "Cartão"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "desconto",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ItemVenda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade", models.PositiveIntegerField()),
                (
                    "preco_unitario",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="loja.produto"
                    ),
                ),
                (
                    "variacao",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="loja.variacao",
                    ),
                ),
                (
                    "venda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="loja.venda"
                    ),
                ),
            ],
        ),
    ]
