# Generated by Django 5.1.7 on 2025-07-27 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loja", "0002_despesa"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
