# Generated by Django 5.1.7 on 2025-07-27 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loja", "0003_produto_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="despesa",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="movimentacaoestoque",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="venda",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
