# Generated by Django 5.1.7 on 2025-07-27 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loja", "0007_alter_categoria_nome"),
    ]

    operations = [
        migrations.AddField(
            model_name="variacao",
            name="estoque_minimo",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="categoria",
            name="nome",
            field=models.CharField(
                choices=[
                    ("Infantil", "Infantil"),
                    ("Feminino", "Feminino"),
                    ("Masculino", "Masculino"),
                ],
                default="--Selecionar--",
                max_length=100,
            ),
        ),
    ]
