# Generated by Django 5.1.7 on 2025-07-27 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loja", "0010_alter_categoria_nome"),
    ]

    operations = [
        migrations.AddField(
            model_name="despesa",
            name="variacao",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="loja.variacao",
            ),
        ),
    ]
