# Generated by Django 5.1.7 on 2025-07-27 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loja", "0013_alter_categoria_nome"),
    ]

    operations = [
        migrations.AddField(
            model_name="venda",
            name="troco",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="venda",
            name="valor_recebido",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="categoria",
            name="nome",
            field=models.CharField(
                choices=[
                    ("Infantil", "Infantil"),
                    ("Feminino", "Feminino"),
                    ("Masculino", "Masculino"),
                ],
                default="--Selecionar--",
                max_length=100,
            ),
        ),
    ]
