# Generated by Django 5.1.7 on 2025-07-28 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loja", "0015_alter_categoria_nome"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categoria",
            name="nome",
            field=models.CharField(
                choices=[
                    ("Masculino", "Masculino"),
                    ("Feminino", "Feminino"),
                    ("Infantil", "Infantil"),
                ],
                default="--Selecionar--",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="produto",
            name="categoria",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="loja.categoria"
            ),
        ),
    ]
