# Generated by Django 5.1.7 on 2025-07-28 00:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loja", "0017_alter_categoria_nome"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="venda",
            name="usuario",
        ),
        migrations.AlterField(
            model_name="categoria",
            name="nome",
            field=models.CharField(
                choices=[
                    ("Feminino", "Feminino"),
                    ("Infantil", "Infantil"),
                    ("Masculino", "Masculino"),
                ],
                default="--Selecionar--",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="venda",
            name="data",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="venda",
            name="desconto",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="venda",
            name="forma_pagamento",
            field=models.CharField(
                choices=[
                    ("DIN", "Dinheiro"),
                    ("PIX", "PIX"),
                    ("CRE", "Crédito"),
                    ("DEB", "Débito"),
                ],
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="venda",
            name="nome_cliente",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="venda",
            name="telefone_cliente",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
