# Generated by Django 5.1.7 on 2025-07-28 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loja", "0018_remove_venda_usuario_alter_categoria_nome_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="venda",
            name="telefone_cliente",
        ),
        migrations.AlterField(
            model_name="categoria",
            name="nome",
            field=models.CharField(
                choices=[
                    ("Masculino", "Masculino"),
                    ("Infantil", "Infantil"),
                    ("Feminino", "Feminino"),
                ],
                default="--Selecionar--",
                max_length=100,
            ),
        ),
    ]
