# Generated by Django 5.1.7 on 2025-07-28 14:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loja", "0019_remove_venda_telefone_cliente_alter_categoria_nome"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="categoria",
            name="nome",
            field=models.CharField(
                choices=[
                    ("Infantil", "Infantil"),
                    ("Feminino", "Feminino"),
                    ("Masculino", "Masculino"),
                ],
                default="--Selecionar--",
                max_length=100,
            ),
        ),
        migrations.CreateModel(
            name="MovimentacaoCaixa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("ENTRADA", "Entrada"), ("SAIDA", "Saída")],
                        max_length=10,
                    ),
                ),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
                ("data", models.DateTimeField(default=django.utils.timezone.now)),
                ("descricao", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "venda",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="loja.venda",
                    ),
                ),
            ],
        ),
    ]
