# Generated by Django 5.1.7 on 2025-07-29 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loja", "0021_alter_categoria_nome"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="produto",
            options={"verbose_name": "Produto", "verbose_name_plural": "Produtos"},
        ),
        migrations.AlterField(
            model_name="categoria",
            name="nome",
            field=models.CharField(
                choices=[
                    ("Infantil", "Infantil"),
                    ("Masculino", "Masculino"),
                    ("Feminino", "Feminino"),
                ],
                default="--Selecionar--",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="produto",
            name="categoria",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="loja.categoria",
            ),
        ),
        migrations.AlterField(
            model_name="produto",
            name="codigo",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="produto",
            name="nome",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="produto",
            name="preco_custo",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
