# Generated by Django 5.1.7 on 2025-07-29 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loja", "0022_alter_produto_options_alter_categoria_nome_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="despesa",
            name="is_manually_created",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="categoria",
            name="nome",
            field=models.CharField(
                choices=[
                    ("Masculino", "Masculino"),
                    ("Feminino", "Feminino"),
                    ("Infantil", "Infantil"),
                ],
                default="--Selecionar--",
                max_length=100,
            ),
        ),
    ]
