# Generated by Django 5.1.7 on 2025-07-30 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loja", "0025_alter_categoria_nome"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemvenda",
            name="preco_custo_historico",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="categoria",
            name="nome",
            field=models.CharField(
                choices=[
                    ("Feminino", "Feminino"),
                    ("Masculino", "Masculino"),
                    ("Infantil", "Infantil"),
                ],
                default="--Selecionar--",
                max_length=100,
            ),
        ),
    ]
