# Generated by Django 5.1.7 on 2025-07-31 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loja", "0027_alter_categoria_nome"),
    ]

    operations = [
        migrations.AddField(
            model_name="movimentacaoestoque",
            name="diferenca_preco",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="movimentacaoestoque",
            name="produto_trocado",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="trocado_em",
                to="loja.variacao",
            ),
        ),
        migrations.AlterField(
            model_name="movimentacaoestoque",
            name="motivo",
            field=models.CharField(
                choices=[
                    ("compra", "Compra"),
                    ("troca", "Troca"),
                    ("devolucao", "Devolução"),
                ],
                default="compra",
                max_length=100,
            ),
        ),
    ]
