# Generated by Django 5.1.7 on 2025-07-31 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loja", "0028_movimentacaoestoque_diferenca_preco_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categoria",
            name="nome",
            field=models.CharField(
                choices=[
                    ("Masculino", "Masculino"),
                    ("Infantil", "Infantil"),
                    ("Feminino", "Feminino"),
                ],
                default="--Selecionar--",
                max_length=100,
            ),
        ),
    ]
